(rules
 (processor
  (post
   (upgrade (lambda (x) x) :<=)))
 (function
  (~s          (x) (symbol->string x))
  (~r          (x) (~a x))
  (apd         (lst) (string-append* lst))
  (mklabel     (x) (string-replace x "-" "_")))
 (macro
  (:-putchar   ()            (:<= ("li a7,11" "ecall")))
  (:-quit      ()            (:<= ("li a7,93" "ecall")))
  (global      (x)           (apd (".globl " (mklabel (~s x)))))
  (signature   (name in out) "")
  (return-value   (name out) "")
  (return      (x)           "")
  (label       (x)           (apd ((mklabel (~s x)) ":")))
  (note        (x)           "")
  (addi        (x y imm)     (apd ("addi " (~s x) "," (~s y) "," (~r imm))))
  (let         (x imm)       (apd ("li " (~s x) "," (~r imm))))
  (-=          (x imm)       (apd ("addi " (~s x) "," (~s x) "," (~r (- 0 imm)))))
  (+=          (x imm)       (apd ("addi " (~s x) "," (~s x) "," (~r imm))))
  (/=          (x y)         (apd ("div " (~s x) "," (~s x) "," (~r y))))
  (=+          (x y z)       (apd ("add " (~s x) "," (~s y) "," (~r z))))
  (=-          (x y z)       (apd ("sub " (~s x) "," (~s y) "," (~s z))))
  (=%          (x y z)       (apd ("rem " (~s x) "," (~s y) "," (~s z))))
  (++          (x)           (apd ("addi " (~s x) "," (~s x) ",1")))
  (--          (x)           (apd ("addi " (~s x) "," (~s x) ",-1")))
  (store-word  (x y imm)     (apd ("sw " (~s x) "," (~r imm) "(" (~s y) ")")))
  (load-word   (x y imm)     (apd ("lw " (~s x) "," (~r imm) "(" (~s y) ")")))
  (load-byte   (x y imm)     (apd ("lbu " (~s x) "," (~r imm) "(" (~s y) ")")))
  (store-byte  (x y imm)     (apd ("sb " (~s x) "," (~r imm) "(" (~s y) ")")))
  (<-          (x y)         (apd ("addi " (~s x) "," (~s y) ",0")))
  (->          (x y)         (apd ("addi " (~s y) "," (~s x) ",0")))
  (call        (label)       (apd ("jal ra," (mklabel (~s label)))))
  (syscall     (x)           (:<= ("ecall")))
  (branch>     (x y label)   (apd ("bgt " (~s x) "," (~s y) "," (mklabel (~s label)))))
  (branch>=    (x y label)   (apd ("bge " (~s x) "," (~s y) "," (mklabel (~s label)))))
  (jump        (label)       (apd ("j " (mklabel (~s label)))))
  (ret         ()            (:<= ("ret")))))

