(:program
 (*** 计算1到100的高斯和并输出结果 ***)
 (:code
  ((global _start)
   (p _start
      (note "计算1到100的和")
      (let t0 1)
      (let t1 100)
      (:f main (t0 t1) (s0))
      (:f print-int (s0))
      (:-quit))
   (*** 主函数 ***)
   (f main (in (int start) (int end)) (out (int result))
      (let t0 0)
      (let t1 0)
      (!for t1 start end
            (:f acc (t0 t1) (s1))
            (<- t0 s1))
      (return (t0)))
   (*** 累加函数:将acc-value加到init-value上 ***)
   (f acc (in (int init-value) (int acc-value)) (out (int result-value))
      (=+ t0 init-value acc-value)
      (return (t0)))
   (*** 函数:打印正整数 ***)
   (f print-int (in (int value))
      (:-stack s0 20)
      (let t0 0)
      (let t1 10)
      (<- t2 value)
      (<- t3 s0)
      (!do-while (compare t2 '> t0)
                 (=% t4 t2 t1)
                 (+= t4 48)
                 (-- t3)
                 (store-byte t4 t3 0)
                 (/= t2 t1))
      (=- t6 s0 t3)
      (:f print-string (t3 t6))
      (:-reclaim s0 20))
   (*** 函数:打印字符串 ***)
   (f print-string (in (int addr) (int len))
      (<- t1 addr)
      (let t2 0)
      (<- t3 len)
      (-- t3)
      (!for t4 t2 t3
            (=+ t5 t1 t4)
            (load-byte t6 t5 0)
            (:s putchar (t6))))
   (*** 系统函数:打印字符 ***)
   (s putchar (in (int ch))
      (<- a0 ch)
      (:-putchar))))
 (:data
  (:string)))
