(rules
 (processor
  (post
   (upgrade (lambda (x) x) :<=)))
 (plugin
  (: local-bind-handler))
 (mapping
  (reg-bytes 8)
  (rs-in     (list ((in int) a) ((in float) fa)))
  (rs-out    (list ((out int) s) ((out float) fs)))
  (rs-in-out (append rs-in rs-out)))
 (function
  (*** 重命名参数为寄存器 ***)
  (*** [todo 优化]为end变量硬指定寄存器,因未完成寄存器分配算法,避免寄存器冲突致运行失败 ***)
  (:rename (lst cfglst)
           (define replace-src (safe car (get-values (second (rename lst cfglst)) '(end))))
           (if (null? replace-src)
               (rename lst cfglst)
               (walk-replace (rename lst cfglst) (list (list replace-src 'a2)))))
  (*** 获取重命名后的别名 ***)
  (:alasmap (lst)
            (safe second lst))
  (*** 取CDR并扁平化 ***)
  (:flatcdr (lst)
            (flatten (map cdr lst)))
  (*** 添加CDR列表 ***)
  (:appendcdr (lst)
              (append* (filter (lambda (t) (not (null? t)))
                               (append* (map (lambda (t) (safe cdr t)) lst)))))
  (*** 替换绑定 ***)
  (:replace (sexp bindings)
            (walk-replace sexp bindings))
  (*** 捕获输入输出 ***)
  (:catch-io (in-regs func-body)
             (let* ((r (filter (lambda (x) (tag? x 'return))
                               func-body))
                    (in (if (null? in-regs) in-regs (list 'in (flatten (map cdr in-regs)))))
                    (out (if (null? r) r (list 'out (second (car r))))))
               (if (null? in)
                   (if (null? out)
                       '()
                       (list out))
                   (if (null? out)
                       (list in)
                       (list in out)))))
  (*** 符号添加后缀 ***)
  (:append-suffix (sym suffix)
                  (string->symbol (string-append (symbol->string sym) "-" suffix))))
 (macro
  (*** 处理过程、函数、系统函数定义 ***)
  (p (procedure-name procedure-body)
     (label procedure-name)
     (:<= procedure-body))
  (f (func-name #:in in-regs #:out out-regs func-body)
     (: arg-maps (:rename (in-regs) rs-in))
     (: ret-maps (:rename (out-regs) rs-out))
     (: args     (:alasmap arg-maps))
     (: rets     (:alasmap ret-maps))
     (: regs     (:flatcdr (append ((ra ra)) rets)))
     (: reg-maps (:appendcdr (arg-maps ret-maps)))
     (: io       (:catch-io args func-body))
     (: fbody    (:replace func-body reg-maps))
     (: epilogue (:append-suffix func-name "epilogue"))
     (!+ signature (append (list func-name) io))
     (label func-name)
     (note "函数序言")
     (push-stack regs)
     (:<=
      fbody)
     (*** label epilogue ***)
     (note "函数尾声")
     (pop-stack regs)
     (ret))
  (s (func-name #:in in-regs #:out out-regs sysfunc-body)
     (: arg-maps (:rename (in-regs) rs-in))
     (: ret-maps (:rename (out-regs) rs-out))
     (: args     (:alasmap arg-maps))
     (: rets     (:alasmap ret-maps))
     (: reg-maps (:appendcdr (arg-maps ret-maps)))
     (: io       (:catch-io args sysfunc-body))
     (: fbody    (:replace sysfunc-body reg-maps))
     (!+ signature (append (list func-name) io))
     (label func-name)
     (:<= fbody)
     (ret))))


