(rules
 (processor
  (post
   (upgrade (lambda (x) x) :<=)))
 (function
  (:label (template id)
          (list 'label
                (symbol-replace template "?" id)))
  (:jump (template id)
         (list 'jump
               (symbol-replace template "?" id)))
  (:branch (condition template id)
           (let ((comp (first condition))
                 (dt1 (second condition))
                 (op (third condition))
                 (dt2 (fourth condition)))
             (list (case op
                     (''=  'branch=)
                     (''<> 'branch<>)
                     (''>  'branch>)
                     (''<  'branch<)
                     (''>= 'branch>=)
                     (''<= 'branch<=)
                     (else #f))
                   dt1
                   dt2
                   (symbol-replace template "?" id))))
  (:branch-not (condition template id)
               (let ((comp (first condition))
                     (dt1 (second condition))
                     (op (third condition))
                     (dt2 (fourth condition)))
                 (list (case op
                         (''=  'branch<>)
                         (''<> 'branch=)
                         (''>  'branch<)
                         (''<  'branch>)
                         (''>= 'branch<=)
                         (''<= 'branch>=)
                         (else #f))
                       dt1
                       dt2
                       (symbol-replace template "?" id))))
  (:branch> (start end template id)
            (list 'branch>
                  start end
                  (symbol-replace template "?" id)))
  (<-> (lst)
       (reverse lst))
  (:rsize (sz reglst)
          (* (length reglst) sz))
  (:foreach (ele index in lst for-body)
            (map (lambda (e i)
                   (walk-replace for-body
                                 (list (list ele e)
                                       (list (first index)
                                             (apply (if (equal? (second index) 'dec) - +)
                                                    (list (third index) (* i (fourth index))))))))
                 lst
                 (range 0 (length lst))))
  (:bind-call (signature name io)
              (let ((sig (get-values signature (list name))))
                (map (lambda (sig-ele io-ele)
                       (list (first sig-ele)
                             (map (lambda (io-reg sig-reg)
                                    (list io-reg sig-reg))
                                  io-ele
                                  (second sig-ele))))
                     sig
                     io)))
  (:assign (reg-list dir)
           (if (null? reg-list) reg-list
               (map (lambda (x)
                      (list dir (first x) (second x)))
                    (car reg-list)))))
 (macro
  (*** 处理if语句 ***)
  (!if (condition if-body)
       (: id (gensym))
       (:branch-not condition if-?-end id)
       (:<= if-body)
       (:label if-?-end id))
  (*** 处理if-else语句 ***)
  (!if-else (condition if-body else-body)
            (: id (gensym))
            (:branch-not condition if-?-else id)
            (:<= if-body)
            (:jump if-?-end id)
            (:label if-?-else id)
            (:<= else-body)
            (:label if-?-end id))
  (*** [todo]处理switch语句 ***)
  (*** 处理while语句 ***)
  (!while (condition while-body)
          (: id (gensym))
          (:label while-?-start id)
          (:branch-not condition while-?-end id)
          (:<= while-body)
          (jump while-?-start id)
          (:label while-?-end id))
  (*** 处理do-while语句 ***)
  (!do-while (condition while-body)
             (: id (gensym))
             (:label while-?-start id)
             (:<= while-body)
             (:branch condition while-?-start id))
  (*** 处理for语句 ***)
  (!for (index start end for-body)
        (: id (gensym))
        (<- index start)
        (:label loop-for-?-cond id)
        (:branch> index end loop-for-?-end id)
        (:<= for-body)
        (++ index)
        (:jump loop-for-?-cond id)
        (:label loop-for-?-end id))
  (*** 处理入栈 ***)
  (push-stack (reg-list)
              (: sz (:rsize reg-bytes (car reg-list)))
              (note "begin push stack")
              (-= sp sz)
              (: sz 0)
              (:<=
               (:foreach r (idx inc sz reg-bytes) in (car reg-list)
                         (store-word r sp idx)))
              (note "end push stack"))
  (*** 处理出栈 ***)
  (pop-stack (reg-list)
             (: sz 0)
             (note "begin pop stack")
             (:<=
              (<->
               (:foreach r (idx inc sz reg-bytes) in (car reg-list)
                         (load-word r sp idx))))
             (: sz (:rsize reg-bytes (car reg-list)))
             (+= sp sz)
             (note "end pop stack"))
  (*** 处理无用指令 ***)
  (note   (x) ())
  (return (x) ())
  (*** 处理栈数据分配与回收 ***)
  (:-stack (var byte-cnt)
           (: sz   (* (car byte-cnt) 4))
           (: off  (- sz reg-bytes))
           (-= sp sz)
           (store-word var sp off)
           (addi var sp sz))
  (:-reclaim (var byte-cnt)
             (: sz   (* (car byte-cnt) 4))
             (: off  (- sz reg-bytes))
             (load-word var sp off)
             (+= sp sz))
  (*** 处理函数调用 ***)
  (:f (name io)
      (: in-regs  (first io))
      (: bindings (:bind-call signature name io))
      (push-stack in-regs)
      (:<=
       (:assign (get-values bindings (in)) ->))
      (call name)
      (:<=
       (:assign (get-values bindings (out)) <-))
      (pop-stack in-regs))
  (:s (name io)
      (: bindings (:bind-call signature name io))
      (:<=
       (:assign (get-values bindings (in)) ->))
      (call name)
      (:<=
       (:assign (get-values bindings (out)) <-)))))


